CREATE DATABASE STICKYNOTES_DB;

SELECT * FROM STICKY_NOTES;

CREATE INDEX REMINDER_DATE_IDX 
ON STICKY_NOTES (REMINDER_DATE);

CREATE INDEX UNIQUE_KEY_IDX 
ON STICKY_NOTES (UNIQUE_KEY);

CREATE TABLE STICKY_NOTES (
     id numeric(10) not null,
	 UNIQUE_KEY varchar(50) not null,
	 TITLE varchar(250) not null,
     DESCRIPTION varchar(5000) not null,
     REMINDER_DATE DATETIME,
     PHONE varchar(15),
     EMAIL varchar(150),
     DATE_CREATED DATETIME,
     PRIMARY KEY (id)
);

INSERT INTO stickynotes_db.sticky_notes
(id, UNIQUE_KEY, TITLE, DESCRIPTION, REMINDER_DATE, PHONE, EMAIL, DATE_CREATED)
VALUES ('1', 'AKEY123232', 'Hello to me', 'This is descr', '2021-12-09 12:00:00', '6039183678', '', '2021-12-09 12:00:00');

SELECT * FROM STICKY_NOTES;

DROP TABLE REMINDER_STAGING;

CREATE TABLE REMINDER_STAGING (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
	 UNIQUE_KEY varchar(50) not null,
	 TITLE varchar(250) not null,
     DESCRIPTION varchar(5000) not null,
     REMINDER_DATE DATETIME,
     PHONE varchar(15),
     EMAIL varchar(150),
     DATE_CREATED DATETIME,
     PRIMARY KEY (id)
);

