DELIMITER $$

CREATE TRIGGER stickynotes_db.STICKY_NOTES_TRIG
    AFTER INSERT
    ON stickynotes_db.STICKY_NOTES FOR EACH ROW
BEGIN
    IF (NEW.REMINDER_DATE IS NOT NULL AND NEW.REMINDER_DATE != '0000-00-00 00:00:00' AND NEW.REMINDER_DATE != '' ) 
        THEN
	        INSERT INTO stickynotes_db.STICKY_NOTES()
            VALUES();
	END IF;
END$$    

DELIMITER ;